spring.application.name=billing-service
server.port=8083
spring.datasource.url=jdbc:h2:mem:billing-db
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://127.0.0.1:9411/api/v2/spans
management.observations.key-values.application=billing-service